import type { Project, Release, Comment, Compatibility } from './types';
const base = {
  owner_id: 'demo-author',
  license: 'MIT',
  github_url: '',
  website_url: '',
  created_at: '2026-09-01T08:00:00Z',
  updated_at: '2026-09-23T08:00:00Z',
  demo: true,
  success_count: 0,
  failure_count: 0,
};
export const demoProjects: Project[] = [
  {
    ...base,
    id: 'demo-macropad',
    slug: 'open-macropad',
    name: 'Open MacroPad',
    author: 'BeiYe',
    summary: '让每一次按下，都恰到好处。为 8 键双旋钮打造的开源固件。',
    description:
      '为创作者和效率爱好者设计的 ESP32-S3 宏键盘固件。\n\n支持 8 个独立机械按键与 2 个旋转编码器，USB HID 即插即用，轻松配置常用快捷键、媒体控制与多步宏。\n\n主要功能\n• 8 个可编程按键，支持多层映射\n• 双旋钮音量、时间轴与画笔控制\n• 逐键 RGB 灯效与 OLED 状态显示\n• 断电保存配置\n\n硬件准备\n请确认 PCB 引脚定义与固件相符。同为 ESP32-S3 不代表硬件兼容。\n\n这是用于预览界面的示例项目，未提供真实固件。',
    chip: 'ESP32-S3',
    device_type: '宏键盘',
    hardware: '8 键 + 双旋钮 MacroPad / Rev 2.0',
    features: ['USB HID', 'RGB', 'OLED', 'Encoder', 'Macro'],
    status: 'stable',
    color: 'orange',
    rating: 4.9,
    flash_count: 12480,
    favorite_count: 2314,
    version: '1.4.2',
  },
  {
    ...base,
    id: 'demo-knob',
    slug: 'dial-one',
    name: 'Dial One',
    author: 'wenzi',
    summary: '一个旋钮，无限可能。精确掌控音量、亮度和你的工作流。',
    description:
      '轻量级旋钮控制器固件，支持旋转、单击与长按操作。\n\n这是用于预览界面的示例项目，未提供真实固件。',
    chip: 'ESP32-C3',
    device_type: '旋钮键盘',
    hardware: 'Dial One 单旋钮 / Rev 1.1',
    features: ['BLE 蓝牙', 'Encoder', 'Media Control'],
    status: 'stable',
    color: 'purple',
    rating: 4.8,
    flash_count: 8620,
    favorite_count: 1420,
    version: '2.0.1',
  },
  {
    ...base,
    id: 'demo-deck',
    slug: 'pixel-deck',
    name: 'Pixel Deck',
    author: 'yuki.dev',
    summary: '属于你的桌面控制中心。小屏幕，大效率。',
    description:
      '为带彩色显示屏的桌面控制器提供自定义快捷操作。\n\n这是用于预览界面的示例项目，未提供真实固件。',
    chip: 'ESP32-S3',
    device_type: 'Stream Deck',
    hardware: 'Pixel Deck 6 键 LCD',
    features: ['USB HID', 'Wi-Fi', 'LCD', 'Macro'],
    status: 'beta',
    color: 'blue',
    rating: 4.7,
    flash_count: 5240,
    favorite_count: 986,
    version: '0.9.0-beta',
  },
  {
    ...base,
    id: 'demo-midi',
    slug: 'midi-lab',
    name: 'MIDI Lab',
    author: 'oscillator',
    summary: '把灵感变成声音。为你的 DIY MIDI 控制器注入灵魂。',
    description:
      '面向音乐创作的开源 MIDI 固件，支持按键和旋钮映射。\n\n这是用于预览界面的示例项目，未提供真实固件。',
    chip: 'ESP32',
    device_type: 'MIDI 控制器',
    hardware: 'MIDI Lab 16 Pad',
    features: ['BLE 蓝牙', 'Encoder', 'RGB'],
    status: 'stable',
    color: 'green',
    rating: 4.8,
    flash_count: 3890,
    favorite_count: 754,
    version: '1.2.0',
  },
  {
    ...base,
    id: 'demo-split',
    slug: 'split-space',
    name: 'Split Space',
    author: 'keebcat',
    summary: '分体设计，自由输入。一套为人体工学键盘打造的固件。',
    description:
      '面向分体式键盘的实验性固件。请在使用前确认接线。\n\n这是用于预览界面的示例项目，未提供真实固件。',
    chip: 'ESP32-S3',
    device_type: '普通键盘',
    hardware: 'Split Space 42 键',
    features: ['USB HID', 'Vial', 'OLED'],
    status: 'experimental',
    color: 'pink',
    rating: 4.6,
    flash_count: 2150,
    favorite_count: 621,
    version: '0.3.2',
  },
  {
    ...base,
    id: 'demo-pocket',
    slug: 'pocket-keys',
    name: 'Pocket Keys',
    author: 'linlin',
    summary: '随身携带的效率工具。极简 4 键，轻松连接。',
    description:
      '小巧的四键蓝牙键盘固件，支持媒体快捷操作。\n\n这是用于预览界面的示例项目，未提供真实固件。',
    chip: 'ESP32-C3',
    device_type: '宏键盘',
    hardware: 'Pocket Keys 4 键',
    features: ['BLE 蓝牙', 'Macro', 'Media Control'],
    status: 'stable',
    color: 'yellow',
    rating: 4.9,
    flash_count: 1860,
    favorite_count: 432,
    version: '1.0.3',
  },
];
export function demoReleases(p: Project): Release[] {
  return [
    {
      id: `${p.id}-release`,
      project_id: p.id,
      version: p.version,
      channel: p.status === 'beta' ? 'beta' : 'stable',
      changelog:
        '优化按键扫描响应，改善设备连接稳定性。\n修复旋钮快速转动时可能出现的重复输入。\n增加更多 RGB 效果与配置选项。',
      hardware: p.hardware,
      manifest: { chip: p.chip, baudRate: 460800, files: [] },
      online_enabled: false,
      created_at: p.updated_at,
    },
  ];
}
export const demoComments: Comment[] = [
  {
    id: 'demo-comment',
    project_id: 'demo-macropad',
    user_id: 'demo-user',
    author: 'momo',
    body: '双旋钮用来调节音量和时间轴很顺手，OLED 显示当前图层也很实用。期待更多自定义灯效！',
    rating: 5,
    device: 'ESP32-S3 · Windows 11 · Chrome',
    created_at: '2026-09-22T08:00:00Z',
  },
];
export const demoCompatibility: Compatibility[] = [
  {
    id: 'demo-report',
    project_id: 'demo-macropad',
    user_id: 'demo-user',
    version_id: 'demo-macropad-release',
    chip: 'ESP32-S3',
    hardware: '8 键 + 双旋钮 / Rev 2.0',
    os: 'Windows 11',
    browser: 'Chrome',
    usb_chip: '原生 USB',
    bluetooth: '未测试',
    rgb: '正常',
    encoder: '正常',
    success: true,
    notes: '示例兼容性记录',
    created_at: '2026-09-22T08:00:00Z',
  },
];
